# Generated by Django 5.2.7 on 2025-11-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0001_initial'),
        ('recipes', '002_dd_default_hashtags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='author',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='content',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='related_article',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='related_recipe',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recipes',
            field=models.ManyToManyField(to='recipes.recipe', verbose_name='Рекомендуемые рецепты'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='recommendation_type',
            field=models.CharField(choices=[('hashtag', 'По хештегам'), ('popular', 'Популярное'), ('trending', 'Трендовое')], max_length=20, verbose_name='Тип рекомендации'),
        ),
    ]
