# Generated by Django 5.2.7 on 2025-11-20 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0002_remove_recommendation_author_and_more'),
        ('recipes', '002_dd_default_hashtags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HashtagSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_count', models.PositiveIntegerField(default=0, verbose_name='Количество поисков')),
                ('last_searched', models.DateTimeField(auto_now=True, verbose_name='Последний поиск')),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_stats', to='recipes.hashtag', verbose_name='Хештег')),
            ],
            options={
                'verbose_name': 'Статистика хештега в поиске',
                'verbose_name_plural': 'Статистика хештегов в поиске',
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, verbose_name='Поисковый запрос')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса')),
                ('results_count', models.PositiveIntegerField(default=0, verbose_name='Количество результатов')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Поисковый запрос',
                'verbose_name_plural': 'Поисковые запросы',
                'ordering': ['-created_at'],
            },
        ),
    ]
