# Generated by Django 5.2.7 on 2025-11-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0003_hashtagsearch_searchquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='statistic_type',
            field=models.CharField(choices=[('daily_visitors', 'Ежедневные посетители'), ('popular_recipes', 'Популярные рецепты'), ('user_activity', 'Активность пользователей'), ('search_queries', 'Поисковые запросы'), ('site_overview', 'Обзор сайта')], max_length=50, verbose_name='Тип статистики'),
        ),
    ]
