# Generated by Django 5.2.7 on 2025-11-24 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0004_alter_statistic_statistic_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_published',
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('rejected', 'Отклонено'), ('pending_review', 'На рассмотрении')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='article',
            name='suggested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_articles', to=settings.AUTH_USER_MODEL, verbose_name='Предложено пользователем'),
        ),
        migrations.CreateModel(
            name='ArticleProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок предложения')),
                ('content', models.TextField(verbose_name='Содержание предложения')),
                ('author_name', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('author_email', models.EmailField(max_length=254, verbose_name='Email автора')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон для связи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата предложения')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Заметки администратора')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата рассмотрения')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Рассмотрено администратором')),
            ],
            options={
                'verbose_name': 'Предложение статьи',
                'verbose_name_plural': 'Предложения статей',
                'ordering': ['-created_at'],
            },
        ),
    ]
