# Generated by Django 5.2.7 on 2025-11-26 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0006_initial_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hashtags',
        ),
    ]
