# Generated by Django 5.2.7 on 2025-11-10 16:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_image'),
        ('recipes', '002_dd_default_hashtags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='CommentArticle',
        ),
    ]
